export enum UserStatues {
    EMAIL_VERIFICATION_PENDING = "EMAIL_VERIFICATION_PENDING",
    ACTIVE = "ACTIVE",
    DEACTIVATED = "DEACTIVATED",
    BANNED = "BANNED"
}


export enum UserRoles {
    ADMIN ="ADMIN",
    CUSTOMER = "CUSTOMER"
}
